# Generated by Django 5.1.5 on 2025-03-31 16:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('API', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HeartRateData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('heart_rate', models.IntegerField()),
                ('user_session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='API.token')),
            ],
        ),
    ]
